interface in_if(input bit clk,rst);
//READ
logic M_ARVALID,M_RREADY,S_ARREADY,S_RVALID;
logic [1:0]S_RRESP;
logic [7:0]RADDR;
logic [7:0]RDATA;

//WRITE
logic M_AWVALID,M_WVALID,M_BREADY,S_AWREADY,S_WREADY;
logic S_BVALID;  // Fix: was [1:0], must be 1-bit handshake signal
logic [7:0]WADDR;
logic [7:0]WDATA;

modport MASTER(input S_ARREADY,S_RVALID,S_RRESP,RDATA,S_AWREADY,S_WREADY,S_BVALID,output M_ARVALID,M_RREADY,RADDR,M_AWVALID,M_WVALID,M_BREADY,WADDR,WDATA);
modport SLAVE(input clk,rst,M_ARVALID,M_RREADY,RADDR,M_AWVALID,M_WVALID,M_BREADY,WADDR,WDATA,output S_ARREADY,S_RVALID,S_RRESP,RDATA,S_AWREADY,S_WREADY,S_BVALID);
endinterface
